export type ReasonTone = "allow" | "deny" | "observe" | "error" | "info" | "unknown";
/** [tone, label, explanation, recommended next step] */
export type ReasonTuple = readonly [ReasonTone, string, string, string];
/**
 * One tuple per reason code: tone, short label, what was observed, recommended next step.
 * Every code the gateway, core and worker sources emit must appear here;
 * tests/request-reasons.test.ts scans those sources and fails on an unmapped one.
 */
export const reasonData: Readonly<Record<string, ReasonTuple>> = {
  // ---- 站点与请求状态 ----
  REQUEST_INCOMPLETE: [
    "observe",
    "请求记录不完整",
    "请求的审计前缀在放行决定或转发意图落盘前中断，或客户端交付未完整结束。",
    "结合请求时间线核对中断点；该状态不代表客户端实际收到的响应。",
  ],
  REQUEST_NOT_CONFIGURED: [
    "deny",
    "无生效站点实现",
    "请求在没有生效站点实现的情况下结束，未转发到源站。",
    "对照站点配置阶段的原因，确认站点已启用并已发布。",
  ],
  SITE_CONFIG_UNAVAILABLE: [
    "error",
    "站点配置不可用",
    "站点策略依赖无法应答，或当前快照中没有匹配该主机与端口的路由。",
    "核对主机名与监听端口是否已发布到当前边缘快照，并检查配置存储。",
  ],
  SITE_DISABLED: [
    "deny",
    "站点已停用",
    "该范围的站点策略被显式停用，请求未被转发到源站。",
    "确认站点是否应保持停用；需要恢复时重新启用并发布配置。",
  ],
  SITE_NOT_CONFIGURED: [
    "deny",
    "站点未配置",
    "请求范围内不存在站点策略，请求未被转发到源站。",
    "核对租户、站点标识与域名路由；必要时先创建并发布站点。",
  ],
  HOST_NOT_ROUTED: [
    "deny",
    "主机未路由",
    "当前边缘快照中没有站点路由该监听端口与 Host，请求不属于任何站点，未被转发。",
    "核对域名、监听端口与已发布的边缘快照；这类拒绝只按端口汇总，不逐条审计。",
  ],
  SKIPPED_BY_SITE_UNAVAILABLE: [
    "unknown",
    "因站点结果而跳过",
    "前序站点策略阶段没有放行，本阶段因此未执行。",
    "查看同一请求站点配置阶段的原因码，按其处理。",
  ],
  // ---- 审计与运行依赖 ----
  AUDIT_DURABILITY_FAILED: [
    "error",
    "审计持久化失败",
    "必需的审计记录未获得持久化确认，相关请求或结果已被拒绝或扣留。",
    "检查审计日志存储与磁盘空间；联系平台管理员并附请求 ID。",
  ],
  AUDIT_TAIL_RECOVERED: [
    "observe",
    "审计日志尾部已修复",
    "启动时发现审计日志尾部因崩溃被截断，已在接收流量前修复。",
    "复核崩溃时间点附近的请求是否缺少终态。",
  ],
  AUDIT_BARRIER_REOPENED: [
    "observe",
    "审计写入器已恢复",
    "持久审计写入器在一次持久化失败后被重新打开，准入已恢复。",
    "核对失败期间被拒绝或扣留的请求，并检查导致失败的审计存储问题。",
  ],
  CLOCK_UNAVAILABLE: [
    "error",
    "可信时钟不可用",
    "准入阶段读取不到可信的系统时间，请求被拒绝。",
    "检查网关主机的系统时钟与时间同步状态。",
  ],
  IDENTITY_STORE_UNAVAILABLE: [
    "error",
    "身份存储不可用",
    "无法安全读取权威身份状态，请求被拒绝。",
    "检查 PostgreSQL 身份存储的连通性与延迟，稍后重试。",
  ],
  // ---- 匿名会话与认证绑定 ----
  ANONYMOUS_SESSION_CAPACITY_EXCEEDED: [
    "deny",
    "匿名会话配额已满",
    "该租户站点的匿名会话数量已达配额上限，未能创建新会话。",
    "检查是否有批量创建会话的来源；必要时调整匿名会话配额。",
  ],
  ANONYMOUS_SESSION_RATE_EXCEEDED: [
    "deny",
    "匿名会话创建过快",
    "匿名会话的创建速率超过了限制。",
    "确认是否为合法突发流量，并排查批量创建会话的来源。",
  ],
  AUTH_BINDING_MISMATCH: [
    "deny",
    "认证绑定不匹配",
    "请求出示的凭证组合与已绑定的组合不一致。",
    "核对 Cookie 与令牌是否属于同一次登录，排查凭证被替换。",
  ],
  AUTH_BINDING_REVOKED: [
    "deny",
    "认证绑定已撤销",
    "服务端已撤销该认证绑定；在身份生命周期阶段表示登出撤销已提交。",
    "请求被拒时用户须重新登录；登出撤销属预期，无需处理。",
  ],
  AUTH_BINDING_VALID: [
    "allow",
    "认证绑定有效",
    "凭证组合与有效绑定完全一致；仅表示身份阶段通过，不代表请求已获授权。",
    "无需处理。",
  ],
  AUTH_CREDENTIAL_GENERATION_CHANGED: [
    "deny",
    "凭证代际已变更",
    "另一次已验证的刷新推进了凭证代际，此前捕获的代际已过期。",
    "使用最新刷新后的凭证重新发起请求。",
  ],
  AUTH_EPOCH_CHANGED: [
    "deny",
    "身份纪元已变更",
    "此前捕获的身份纪元（epoch）已不是最新，账号上下文发生过变化。",
    "让用户刷新页面或重新登录后再重试。",
  ],
  AUTH_REQUIRED: [
    "deny",
    "需要认证",
    "请求没有已认证的身份绑定，却访问了需要登录的操作。",
    "调用方须先登录以建立认证绑定，再重试。",
  ],
  AUTH_SESSION_EXPIRED: [
    "deny",
    "会话已过期",
    "服务端会话租约已到期，认证绑定不再有效。",
    "用户需重新登录以建立新会话。",
  ],
  // ---- 身份生命周期 ----
  BINDING_CREATED: [
    "info",
    "认证绑定已创建",
    "认证响应通过校验后，身份事务已提交并建立了认证绑定。",
    "无需处理。",
  ],
  IDENTITY_CONTEXT_CHANGED: [
    "info",
    "身份上下文已切换",
    "账号上下文变化已提交，身份纪元与凭证代际均已递增。",
    "如非预期，对照切换前后的主体与授权上下文。",
  ],
  IDENTITY_REFRESHED: [
    "info",
    "身份凭证已刷新",
    "同一账号上下文内的凭证刷新已提交，凭证代际已递增。",
    "无需处理。",
  ],
  SESSION_CREATED: [
    "info",
    "匿名会话已创建",
    "身份事务已提交，已创建匿名会话；创建后的请求仍需认证。",
    "无需处理。",
  ],
  // ---- 准入与操作匹配 ----
  AUTH_ENTRY_ALLOWED: [
    "allow",
    "认证入口已准入",
    "精确的认证操作入口通过准入；仅表示入口匹配，不代表登录成功。",
    "无需处理。",
  ],
  FLOW_ROOT_ALLOWED: [
    "allow",
    "流程根已准入",
    "已认证的流程根操作通过准入；仅表示准入阶段通过。",
    "无需处理。",
  ],
  OPERATION_NOT_MATCHED: [
    "deny",
    "操作未匹配",
    "请求的方法或路由与已冻结的操作策略不匹配。",
    "核对请求的方法与路径是否为站点已声明的操作。",
  ],
  PUBLIC_ENTRY_ALLOWED: [
    "allow",
    "公开入口已准入",
    "精确的公开操作入口通过准入；仅表示入口匹配，不代表业务成功。",
    "无需处理。",
  ],
  PAGE_ROOT_SESSION_ALLOWED: [
    "allow",
    "页面根按会话放行",
    "不带 Authorization 的页面顶层导航，已按仍有效的 WAF 会话识别身份并放行；随后签发的一切仍绑定该身份与代际。",
    "无需处理。",
  ],
  UI_ACTION_ALLOWED: [
    "allow",
    "界面动作已准入",
    "界面动作与资源要求的精确校验通过；仅表示该阶段通过。",
    "无需处理。",
  ],
  // ---- 资格（Grant） ----
  CAPABILITY_MISSING: [
    "deny",
    "缺少资源资格",
    "当前身份对所请求的资源没有有效的精确资格。",
    "核实访问是否合法；手工拼接或枚举 ID 被拒绝属预期。",
  ],
  GRANT_ALREADY_ISSUED: [
    "info",
    "资格已发行过",
    "相同发行键解析为原有资格，没有新建资格。",
    "无需处理。",
  ],
  GRANT_CAPACITY_EXCEEDED: [
    "error",
    "资格账本容量已满",
    "资格账本已达配置的硬容量上限，未能新发行资格。",
    "检查资格账本的清理与容量配置；联系平台管理员。",
  ],
  GRANT_EXPIRY_INVALID: [
    "deny",
    "资格期限无效",
    "资格草案的时间界限无效，未能发行。",
    "核对资格期限非空且不超过动作与证据的期限。",
  ],
  GRANT_ISSUANCE_CONFLICT: [
    "deny",
    "资格发行键冲突",
    "同一幂等键被用于不同的授权语义，发行被拒绝。",
    "改用新的幂等键，或沿用原键与完全一致的参数。",
  ],
  GRANT_ISSUED: [
    "allow",
    "资格已发行",
    "新的精确资格及其发行事件已提交；发行记录不证明资格当前仍有效。",
    "无需处理。",
  ],
  GRANT_SOURCE_INELIGIBLE: [
    "deny",
    "资格来源不合格",
    "身份、已批准动作、策略或租约不满足发行资格的条件。",
    "核对绑定、动作、策略修订与租约是否仍有效。",
  ],
  OPERATION_NOT_GRANTED: [
    "deny",
    "操作未被授予",
    "资源已有资格，但未授予所请求的操作或视图。",
    "核对资格中的 operation 与 view 是否覆盖本次请求。",
  ],
  // ---- 界面动作来源 ----
  FIELD_NOT_ALLOWED: [
    "deny",
    "字段不在许可范围",
    "请求包含已批准动作配置之外的字段。",
    "移除多余字段，或核对动作配置允许的字段集合。",
  ],
  TARGET_SCOPE_MISMATCH: [
    "deny",
    "动作目标越权",
    "动作目标超出已批准的主体或资源范围。",
    "核对请求目标是否为已验证主体或已批准的资源范围。",
  ],
  UI_ACTION_ALREADY_ISSUED: [
    "info",
    "界面动作已发行过",
    "相同的动作资格此前已提交，本次沿用原记录。",
    "无需处理。",
  ],
  UI_ACTION_CAPACITY_EXCEEDED: [
    "deny",
    "动作引用容量已满",
    "页面签发时，该身份可持有的未过期动作引用已达容量上限，本次没有发行引用；页面照常交付，其受保护请求会因没有引用而被拒绝。",
    "等待旧引用到期或撤销后重新打开页面；持续出现时核对页面声明的动作数量。",
  ],
  UI_ACTION_EXPIRY_INVALID: [
    "deny",
    "动作期限无效",
    "动作资格的时间界限无效，未能发行。",
    "核对动作期限非空且不超过页面证据与会话的期限。",
  ],
  UI_ACTION_ISSUANCE_CONFLICT: [
    "deny",
    "动作引用冲突",
    "同一动作引用被用于不同语义，发行被拒绝。",
    "改用新的动作引用，或沿用原引用与一致的参数。",
  ],
  UI_ACTION_ISSUED: [
    "allow",
    "界面动作已发行",
    "已验证的页面证据与新的精确动作资格已提交；发行不代表动作已执行。",
    "无需处理。",
  ],
  UI_ACTION_NOT_AVAILABLE: [
    "deny",
    "界面动作不可用",
    "没有为已验证的页面登记可用的动作映射，请求被拒绝。",
    "核对站点的界面动作映射与页面证据；确认该页面是否应开放此操作。",
  ],
  UI_DESCRIPTOR_CONFLICT: [
    "error",
    "动作描述冲突",
    "边缘启动时发现，同一策略修订下的动作描述与已登记的不一致，已拒绝启动且不覆盖已有记录。",
    "改变页面动作后发布新的策略修订；不要在原修订下改写动作描述。",
  ],
  UI_EVIDENCE_UNVERIFIED: [
    "deny",
    "页面证据未验证",
    "页面证据未经验证，或已过期、已被撤销。",
    "核对页面构建是否已验证并映射；过期或撤销后需重新生成。",
  ],
  // ---- 分享与服务身份 ----
  SERVICE_IDENTITY_ALLOWED: [
    "allow",
    "服务身份已准入",
    "服务身份的精确操作范围校验通过；仅表示该阶段通过。",
    "无需处理。",
  ],
  SERVICE_IDENTITY_MISMATCH: [
    "deny",
    "服务身份不匹配",
    "服务身份凭证与所请求的操作范围不匹配。",
    "核对服务凭证有效、未过期，且其操作集合包含本次请求。",
  ],
  SHARE_ALREADY_ISSUED: [
    "info",
    "分享资格已发行过",
    "相同发行键解析为原有分享资格，没有新建。",
    "无需处理。",
  ],
  SHARE_CAPACITY_EXCEEDED: [
    "deny",
    "活跃分享数已满",
    "发行者的活跃分享数量已达配置上限。",
    "等现有分享到期或撤销后再发行，或评估上限设置。",
  ],
  SHARE_ENTRY_ALLOWED: [
    "allow",
    "分享入口已准入",
    "精确的有限分享凭证校验通过；仅表示该阶段通过。",
    "无需处理。",
  ],
  SHARE_ISSUANCE_CONFLICT: [
    "deny",
    "分享发行键冲突",
    "同一发行键被用于不同的授权语义，发行被拒绝。",
    "改用新的发行键，或沿用原键与完全一致的参数。",
  ],
  SHARE_ISSUED: [
    "allow",
    "分享资格已发行",
    "新的有限分享资格及其发行事件已提交；不代表凭证已被使用。",
    "无需处理。",
  ],
  SHARE_SCOPE_MISMATCH: [
    "deny",
    "分享范围不匹配",
    "分享凭证与所请求的资源、视图、操作或租约不匹配。",
    "核对分享是否过期、被撤销或被用于其他资源。",
  ],
  SHARE_SOURCE_INELIGIBLE: [
    "deny",
    "分享来源不合格",
    "发行者身份、资源资格、规则、策略或租约不满足分享条件。",
    "核对发行者的资格、分享规则与租约是否仍有效。",
  ],
  // ---- WAF 与限流 ----
  SITE_RATE_LIMIT_EXCEEDED: [
    "deny",
    "站点限流",
    "该来源在站点范围内的请求速率超过了限制。",
    "确认是否为合法突发流量；必要时调整站点限流策略。",
  ],
  WAF_COOKIE_TOO_LARGE: [
    "deny",
    "Cookie 过大",
    "Cookie 请求头总长度超过站点 WAF 配置的上限。",
    "清理多余 Cookie；确需放宽时调整站点 WAF 上限。",
  ],
  WAF_HEADER_BLOCKED: [
    "deny",
    "WAF 拦截请求头",
    "站点 WAF 规则拦截了请求中被配置禁止的请求头。",
    "确认该请求头应否被拦截；误拦时调整规则并发布新修订。",
  ],
  WAF_QUERY_BLOCKED: [
    "deny",
    "WAF 拦截查询参数",
    "严格百分号解码后，查询串命中了站点配置的拦截片段。",
    "用正常业务样本核对是否误拦；必要时发布新策略修订。",
  ],
  WAF_QUERY_INVALID: [
    "deny",
    "查询串无法解码",
    "查询串无法被无歧义地解码（编码畸形、过长或含控制字符）。",
    "客户端须使用规范的百分号编码并缩短查询串。",
  ],
  // ---- 加密请求与重放防护 ----
  REQUEST_BODY_TOO_LARGE: [
    "deny",
    "请求体过大",
    "请求体或加密封包超过站点允许的大小上限，请求被拒绝。",
    "调用方须缩小请求体；确需更大时由管理员调整站点限制。",
  ],
  REQUEST_BUFFER_CAPACITY_EXHAUSTED: [
    "error",
    "请求缓冲容量不足",
    "请求缓冲的聚合容量暂时不足，请求未能处理。",
    "稍后重试；持续出现请联系平台管理员评估缓冲容量。",
  ],
  REQUEST_CRYPTO_AUTHENTICATION_FAILED: [
    "deny",
    "认证解密失败",
    "加密请求未通过认证解密，明文未被放行。",
    "核对客户端适配器版本与密钥标识，排查封包被篡改。",
  ],
  REQUEST_CRYPTO_BUILD_NOT_APPROVED: [
    "deny",
    "页面构建未获批准",
    "已验证的页面证据与任何已批准的兼容构建都不匹配。",
    "确认该页面构建是否应纳入兼容审批的构建范围。",
  ],
  REQUEST_CRYPTO_COMPATIBILITY_EXPIRED: [
    "deny",
    "兼容审批已过期",
    "兼容性审批在请求准入前已过期，请求被拒绝。",
    "续期兼容审批，或迁移到强制解密模式。",
  ],
  REQUEST_CRYPTO_COMPATIBILITY_OPAQUE: [
    "observe",
    "兼容模式透传密文",
    "已批准的兼容范围内，加密请求体未经解密校验，按原样转发。",
    "关注兼容审批的到期时间与构建范围，按期迁移。",
  ],
  REQUEST_CRYPTO_DECODED: [
    "allow",
    "请求已解密",
    "认证解密成功，明文已通过校验并冻结，用于重建发往源站的请求。",
    "无需处理。",
  ],
  REQUEST_CRYPTO_KEY_UNAVAILABLE: [
    "error",
    "请求解密密钥不可用",
    "无法获取该范围的请求解密密钥，请求无法解密。",
    "检查站点请求解密密钥的配置与有效期；联系平台管理员。",
  ],
  REQUEST_CRYPTO_MESSAGE_EXPIRED: [
    "deny",
    "请求消息已过期",
    "已认证的请求消息在重放消费前已过期。",
    "客户端须保持时钟同步并重新生成请求消息。",
  ],
  REQUEST_CRYPTO_MESSAGE_FROM_FUTURE: [
    "deny",
    "请求消息时间超前",
    "已认证的请求消息签发时间超出允许的时钟偏差。",
    "校准客户端系统时钟后重新发起请求。",
  ],
  REQUEST_CRYPTO_OBSERVED_OPAQUE: [
    "observe",
    "观察模式透传密文",
    "观察模式下加密请求体未经解密校验，按原样转发给源站。",
    "评估后可在站点配置中切换到强制解密。",
  ],
  REQUEST_CRYPTO_REPLAY_CAPACITY_EXCEEDED: [
    "error",
    "重放账本容量已满",
    "权威重放账本的活动记录已达配置上限，请求被拒绝。",
    "检查重放账本的清理与上限配置；联系平台管理员。",
  ],
  REQUEST_CRYPTO_REPLAY_DETECTED: [
    "deny",
    "检测到请求重放",
    "该请求的 nonce 或消息标识已被消费，判定为重放。",
    "客户端须为每次请求生成新的 nonce 与消息标识；排查重放来源。",
  ],
  REQUEST_CRYPTO_REPLAY_STORE_UNAVAILABLE: [
    "error",
    "重放账本不可用",
    "权威重放账本无法安全消费该消息，请求被拒绝。",
    "检查重放账本所在数据库的连通性后重试。",
  ],
  REQUEST_ENVELOPE_INVALID: [
    "deny",
    "加密封包无效",
    "加密请求的分帧、媒体类型、封包、版本或明文未通过校验。",
    "调用方须按约定的封包格式重新构造请求。",
  ],
  // ---- 响应校验与加密 ----
  RESPONSE_BODY_TOO_LARGE: [
    "deny",
    "响应体超出缓冲上限",
    "受保护响应超过完整缓冲上限，响应被拦截。",
    "核对该操作配置的响应体大小上限与源站实际响应大小。",
  ],
  RESPONSE_BUFFER_CAPACITY_EXHAUSTED: [
    "error",
    "响应缓冲容量不足",
    "响应缓冲的聚合容量暂时不足，无法处理该响应。",
    "稍后重试；持续出现请联系平台管理员评估缓冲容量。",
  ],
  RESPONSE_CRYPTO_ENCODED: [
    "allow",
    "响应已加密",
    "转换后的源站响应已为客户端加密；不代表客户端已收到或解密。",
    "无需处理。",
  ],
  RESPONSE_CRYPTO_ENCODING_FAILED: [
    "error",
    "响应加密失败",
    "响应加密或所需随机数获取失败，响应未被放行。",
    "检查网关主机的加密库与随机数来源；联系平台管理员。",
  ],
  RESPONSE_CRYPTO_ENVELOPE_TOO_LARGE: [
    "deny",
    "加密响应超限",
    "加密后的响应封包超过配置的序列化上限。",
    "核对响应大小与封包上限配置，必要时调整。",
  ],
  RESPONSE_CRYPTO_KEY_UNAVAILABLE: [
    "error",
    "响应加密密钥不可用",
    "无法获取该范围的响应加密密钥，响应未被加密放行。",
    "检查站点响应加密密钥的配置与有效期；联系平台管理员。",
  ],
  RESPONSE_VALIDATION_FAILED: [
    "deny",
    "响应校验失败",
    "受保护响应未通过分帧、编码、媒体类型或 JSON 校验，已被拦截。",
    "核对源站响应格式是否符合该操作的响应契约。",
  ],
  // ---- 浏览器传感器 ----
  SENSOR_ACTIONS_DELIVERED: [
    "info",
    "动作引用已交付",
    "传感器 1.1.0 的引导响应交付了当前页面的至少一个动作引用；审计只记录数量，引用本身不进入审计。",
    "无需处理。",
  ],
  SENSOR_ACTIONS_UNAVAILABLE: [
    "observe",
    "没有可交付的动作引用",
    "引导响应没有可交付的动作引用（页面未签发、已过期或已撤销），传感器无法为请求附带引用，页面的受保护请求会被拒绝。",
    "核对页面是否在交付时签发了动作、引用是否已过期；重新打开页面后重试。",
  ],
  SENSOR_ASSET_SERVED: [
    "info",
    "传感器资源已提供",
    "边缘提供了带版本的浏览器传感器资源文件。",
    "无需处理。",
  ],
  SENSOR_BOOTSTRAP_INVALID: [
    "deny",
    "传感器引导请求无效",
    "引导请求的查询串不是受支持的形态（页面句柄缺失或畸形），已以 400 拒绝。",
    "核对加载器版本与页面注入的 data-xshield-page 句柄；通常来自客户端异常或探测流量。",
  ],
  SENSOR_BOOTSTRAP_SERVED: [
    "info",
    "传感器引导已提供",
    "边缘提供了动态生成的浏览器传感器引导脚本。",
    "无需处理。",
  ],
  SENSOR_HTML_INJECTED: [
    "info",
    "传感器脚本已注入",
    "已向精确批准的 HTML 响应注入带版本的传感器脚本。",
    "无需处理。",
  ],
  SENSOR_HTML_VALIDATION_FAILED: [
    "error",
    "传感器注入失败",
    "HTML 传感器注入的校验或改写失败，响应已按失败即拒绝处理。",
    "核对源站 HTML 的媒体类型、编码与 CSP；联系平台管理员。",
  ],
  SENSOR_LOADER_SERVED: [
    "info",
    "传感器加载器已提供",
    "边缘提供了不可变的浏览器传感器引导加载器。",
    "无需处理。",
  ],
  SENSOR_OBSERVATION_ACCEPTED: [
    "info",
    "传感器观察已接收",
    "绑定会话的浏览器观察数据已被持久接收；不代表该浏览器可信。",
    "无需处理。",
  ],
  SENSOR_OBSERVATION_INVALID: [
    "deny",
    "传感器观察无效",
    "浏览器观察数据的分帧或内容未通过严格校验，已被拒绝。",
    "核对传感器版本与构建标识；异常来源按请求 ID 追查。",
  ],
  // ---- 源站转发 ----
  ORIGIN_FORWARD_INTENT_RECORDED: [
    "info",
    "转发意图已记录",
    "转发意图已达到持久化边界；这不证明源站已收到或执行了请求。",
    "需确认源站结果时，查看同一请求的源站响应事件。",
  ],
  ORIGIN_OUTCOME_UNKNOWN: [
    "unknown",
    "源站结果未知",
    "代理失败后无法确定源站是否已产生副作用。",
    "由业务方经源站幂等或状态查询确认真实副作用（RB-07）。",
  ],
  ORIGIN_RESPONSE_RECEIVED: [
    "info",
    "已收到源站响应",
    "网关收到了所选源站的响应；不代表业务操作成功或客户端已收到。",
    "业务结果以源站记录为准。",
  ],
  // ---- 证据采集 ----
  EVIDENCE_CAPTURED: [
    "info",
    "证据已采集",
    "响应证据已加密落盘、登记目录并写入审计，原文需经审批读取。",
    "无需处理；读取原文须走证据访问申请。",
  ],
  EVIDENCE_CAPTURE_CAPACITY_EXHAUSTED: [
    "error",
    "证据采集容量用尽",
    "证据采集的并发、字节配额或文件配额已用尽。",
    "检查证据库容量与保留策略，清理或扩容后重试。",
  ],
  EVIDENCE_CAPTURE_INVALID: [
    "deny",
    "证据采集校验失败",
    "响应体未通过证据采集的严格 JSON 解析或密钥策略校验。",
    "核对源站响应是否为合法 JSON（无重复键）并符合采集配置。",
  ],
  EVIDENCE_CAPTURE_LIMIT_EXCEEDED: [
    "deny",
    "证据采集超限",
    "证据来源、输出或排除清单超出了配置上限。",
    "核对采集配置的大小上限与源站响应体大小。",
  ],
  EVIDENCE_CAPTURE_UNAVAILABLE: [
    "error",
    "证据采集不可用",
    "必需的加密证据存储或目录发布失败，响应已被扣留。",
    "检查证据库与证据目录（PostgreSQL）的可用性。",
  ],
  EVIDENCE_CATALOG_PUBLISHED: [
    "info",
    "证据目录已发布",
    "加密证据对象已登记到证据目录。",
    "无需处理。",
  ],
  EVIDENCE_SECRET_EXCLUDED: [
    "info",
    "密钥字段已排除",
    "采集文档中的密钥类字段已按策略置空，原值不会保留。",
    "无需处理；该字段原值在证据中不可恢复。",
  ],
  // ---- 边缘配置下发 ----
  EDGE_HEALTH_REQUEST_EXPIRED: [
    "deny",
    "健康探测请求已过期",
    "边缘健康探测请求的签名时间已超出允许范围，被拒绝。",
    "核对控制面与边缘主机的时钟同步后重试。",
  ],
  EDGE_HEALTH_REQUEST_REPLAYED: [
    "deny",
    "健康探测请求被重放",
    "边缘健康探测请求的随机数此前已使用过，被作为重放拒绝。",
    "重新发起一次带新随机数的探测；反复出现请排查请求被截获重放。",
  ],
  EDGE_HEALTH_RATE_LIMITED: [
    "deny",
    "健康探测过于频繁",
    "边缘健康探测请求超过了频率上限，被限流。",
    "降低探测频率，稍后重试。",
  ],
  EDGE_APPLY_CONFIRMED: [
    "allow",
    "下发已确认",
    "边缘已验证并启用该配置快照，对应修订已生效。",
    "无需处理。",
  ],
  EDGE_APPLY_DESCRIPTOR_CONFLICT: [
    "deny",
    "下发动作描述冲突",
    "快照中某站点由配置推导的界面动作描述与该策略修订已登记的描述不一致（摘要不同、修订不是 active 或描述含义改变），整份下发被拒绝。",
    "改变页面动作、路由或映射须使用新的策略修订号；应答中的 site_id 指明出问题的站点。",
  ],
  EDGE_APPLY_DESCRIPTOR_UNAVAILABLE: [
    "error",
    "动作描述供给不可用",
    "边缘无法把站点的界面动作描述写入 PostgreSQL（数据库不可达、超时或未配置身份存储），整份下发未生效。",
    "恢复数据库连接，或为边缘配置身份存储后重新下发；应答中的 site_id 指明该站点。",
  ],
  EDGE_APPLY_IDEMPOTENCY_CONFLICT: [
    "deny",
    "下发修订冲突",
    "同一修订号已生效，但本次快照内容摘要不同，下发被拒绝。",
    "变更须使用新的修订号，勿复用已生效的修订号。",
  ],
  EDGE_APPLY_LISTENER_UNAVAILABLE: [
    "error",
    "监听端口不可用",
    "新快照所需的监听端口无法绑定，下发未生效。",
    "检查端口占用与权限，换用可用端口后重新下发。",
  ],
  EDGE_APPLY_PAYLOAD_INVALID: [
    "deny",
    "下发请求体无效",
    "下发请求体无法解析为有效的下发请求。",
    "核对下发请求的 JSON 结构与字段。",
  ],
  EDGE_APPLY_SCOPE_DENIED: [
    "deny",
    "下发租户不一致",
    "下发请求的租户与该边缘节点绑定的租户不一致。",
    "确认下发目标节点与租户标识匹配。",
  ],
  EDGE_APPLY_SIGNATURE_INVALID: [
    "deny",
    "下发签名无效",
    "下发请求缺少有效签名，或签名校验未通过。",
    "核对控制面与边缘节点的下发签名配置是否一致。",
  ],
  EDGE_APPLY_SIGNATURE_UNAVAILABLE: [
    "error",
    "下发签名不可用",
    "边缘节点无法计算签名，不能校验下发请求。",
    "检查边缘节点的下发签名配置；联系平台管理员。",
  ],
  EDGE_APPLY_STALE_REVISION: [
    "deny",
    "下发修订过旧",
    "下发的修订号低于边缘当前生效的修订号，已被拒绝。",
    "确认控制面下发的修订不低于当前生效的修订。",
  ],
  EDGE_APPLY_VALIDATION_FAILED: [
    "deny",
    "下发快照校验失败",
    "下发的配置快照未通过边缘校验（HTTP 422）。",
    "按站点配置校验结果修正后重新下发。",
  ],
  EDGE_SNAPSHOT_PERSISTENCE_UNAVAILABLE: [
    "error",
    "快照持久化不可用",
    "签名快照无法持久保存；提升失败时边缘会停止数据面监听。",
    "立即检查边缘快照卷的空间与权限，修复后重新下发。",
  ],
  // ---- 模型评估生命周期 ----
  MODEL_CACHE_HIT: [
    "info",
    "命中模型缓存",
    "本次评估复用了已校验的缓存结果，没有向供应商发送请求。",
    "无需处理；来源调用见事件中的缓存来源 ID。",
  ],
  MODEL_CANCELLED: [
    "observe",
    "模型评估被取消",
    "评估在取得完整响应前被取消，供应商是否已处理该请求未知。",
    "需要结果时重新发起评估。",
  ],
  MODEL_EVALUATED: [
    "info",
    "模型评估完成",
    "模型调用与证据取证已完成并通过响应校验；不表示业务操作获准。",
    "无需处理；详情需经证据访问申请读取。",
  ],
  MODEL_EVALUATION_STARTED: [
    "info",
    "模型评估已开始",
    "一次离线模型评估已创建并开始审计，此时尚未向供应商发出请求。",
    "无需处理；结果见同一调用的后续事件。",
  ],
  MODEL_OUTCOME_UNKNOWN: [
    "unknown",
    "模型结果未知",
    "评估在终态写入前中断，重启恢复时补记为结果未知，供应商是否已计费未知。",
    "需要结果时重新发起评估。",
  ],
  MODEL_REQUESTED: [
    "info",
    "模型请求已冻结",
    "实际请求内容已冻结并持久记录，将向供应商发出单次请求；不代表供应商已收到。",
    "无需处理；结果见同一调用的终态事件。",
  ],
  MODEL_TIMEOUT: [
    "error",
    "模型调用超时",
    "向模型供应商的请求超过截止时间，未取得完整响应。",
    "稍后重试；持续超时请检查供应商状态与出站网络。",
  ],
  // ---- 模型供应商交互 ----
  MODEL_HTTP_ERROR: [
    "error",
    "模型供应商 HTTP 错误",
    "模型供应商返回了非 200 的 HTTP 状态。",
    "在调用记录中查看 HTTP 状态与供应商请求 ID。",
  ],
  MODEL_OVERLOADED: [
    "error",
    "模型供应商过载",
    "模型供应商返回 529，当前处于过载状态。",
    "稍后重试；持续出现请联系供应商。",
  ],
  MODEL_RATE_LIMITED: [
    "error",
    "模型供应商限流",
    "模型供应商返回 429，本次评估被限流。",
    "按 Retry-After 提示稍后重试；评估器不会自动重试。",
  ],
  MODEL_RESPONSE_INVALID: [
    "error",
    "模型响应无效",
    "供应商响应的响应头或结构未通过严格校验，规范化结果为空。",
    "经证据访问申请查看已保存的原始响应捕获。",
  ],
  MODEL_RESPONSE_TOO_LARGE: [
    "error",
    "模型响应过大",
    "供应商响应超过 64 KiB 读取上限，仅保存了已读取的部分。",
    "该捕获不完整，不能当作完整结果使用。",
  ],
  MODEL_TRANSPORT_ERROR: [
    "error",
    "模型传输失败",
    "与模型供应商的 HTTPS 交互失败，未取得完整响应。",
    "检查出站网络、DNS 与 TLS，稍后重试。",
  ],
  // ---- 模型评估配置与输入 ----
  OFFLINE_EVALUATION: [
    "unknown",
    "离线评估，证据不可用",
    "该样本在离线评估中进行，输入里的认证事实或页面证据被标记为不可用。",
    "无需处理；这不代表在线请求缺少这些证据。",
  ],
  MODEL_CONFIG_INVALID: [
    "error",
    "模型评估配置无效",
    "模型评估所需的部署配置缺失或无效。",
    "核对评估器环境配置，并确认各类密钥相互独立。",
  ],
  MODEL_ENDPOINT_INVALID: [
    "error",
    "模型端点无效",
    "模型供应商端点地址不符合固定要求。",
    "核对评估器使用的端点配置。",
  ],
  MODEL_INPUT_INVALID: [
    "deny",
    "评估输入无效",
    "评估输入文件未通过校验（路径、权限、大小或结构）。",
    "确认输入为仅属主可访问、不超过 8 KiB 的普通 JSON 文件。",
  ],
  MODEL_KEY_INVALID: [
    "error",
    "模型凭证格式无效",
    "供应商 API 凭证的长度或字符不符合要求。",
    "核对注入评估器的 API 凭证是否完整、无多余空白。",
  ],
  MODEL_RUNTIME_UNAVAILABLE: [
    "error",
    "运行时不满足要求",
    "评估需要多线程异步运行时，当前运行时不满足要求。",
    "使用官方评估入口（多线程运行时）运行。",
  ],
  MODEL_SECRET_EXCLUDED: [
    "deny",
    "凭证内容已排除",
    "检测到内容含有供应商凭证，已按策略排除，相关内容未发送或未保存。",
    "清理输入或排查供应商回显凭证的原因，必要时轮换凭证。",
  ],
  // ---- 模型结果缓存 ----
  MODEL_CACHE_CONFIG_INVALID: [
    "error",
    "缓存配置无效",
    "模型结果缓存的安全域、密钥或模型标识配置无效。",
    "核对缓存安全域与缓存密钥配置，缓存密钥须独立于其他密钥。",
  ],
  MODEL_CACHE_EXACT_REVISION_REQUIRED: [
    "deny",
    "缓存需要精确修订",
    "缓存要求调用前可证明精确模型修订，当前路由无法提供。",
    "改用可证明精确修订的 direct 路由，或不启用缓存。",
  ],
  MODEL_CACHE_SOURCE_INVALID: [
    "error",
    "缓存来源校验失败",
    "缓存来源条目缺失、过期、被篡改或版本漂移，未复用缓存。",
    "核对来源证据与目录是否被改动；联系平台管理员。",
  ],
  MODEL_CACHE_SOURCE_UNAVAILABLE: [
    "error",
    "缓存来源不可用",
    "读取缓存来源证据时依赖不可用或超时，未复用缓存。",
    "检查证据目录与证据库的可用性后重试。",
  ],
  MODEL_CACHE_UNAVAILABLE: [
    "error",
    "缓存查找不可用",
    "查找模型缓存时数据库失败或超时，评估被终止。",
    "检查 PostgreSQL 连接后重试。",
  ],
  // ---- 模型评估存储与恢复 ----
  MODEL_AUDIT_CAPACITY: [
    "error",
    "评估审计日志已近上限",
    "评估专用审计日志剩余空间不足，未开始新的评估。",
    "按运维手册 RB-11 轮换或扩容评估审计日志目录。",
  ],
  MODEL_AUDIT_UNAVAILABLE: [
    "error",
    "评估审计日志不可用",
    "评估专用审计日志无法写入或校验，评估被阻止或终态未能记录。",
    "检查评估审计日志目录；重启后会补记未完成调用。",
  ],
  MODEL_CATALOG_CONFLICT: [
    "error",
    "证据目录登记冲突",
    "证据目录登记与已有记录冲突，对象未能发布。",
    "联系平台管理员排查同一证据标识的重复登记。",
  ],
  MODEL_CATALOG_UNAVAILABLE: [
    "error",
    "证据目录不可用",
    "证据目录（PostgreSQL）无法连接或写入，评估被阻止或终止。",
    "检查 PostgreSQL 连通性与迁移状态后重试。",
  ],
  MODEL_EVIDENCE_CAPACITY: [
    "error",
    "评估证据容量不足",
    "评估证据存储的字节或文件配额不足，不再写入新证据。",
    "清理或扩容评估证据根目录后重试。",
  ],
  MODEL_EVIDENCE_UNAVAILABLE: [
    "error",
    "评估证据存储不可用",
    "评估证据对象无法写入或读取，评估被终止。",
    "检查证据根目录的挂载、权限与磁盘空间后重试。",
  ],
  MODEL_RECOVERY_FAILED: [
    "error",
    "评估恢复失败",
    "启动时认证扫描评估审计日志失败，已拒绝开始新的评估。",
    "核对评估审计日志目录的完整性，修复后再运行。",
  ],
  // ---- 模型评估准入 ----
  MODEL_EVALUATION_ADMISSION_CONFLICT: [
    "deny",
    "评估租约冲突",
    "该模型调用标识与已存在的不兼容租约冲突，准入被拒绝。",
    "排查是否重复提交了同一调用；联系平台管理员。",
  ],
  MODEL_EVALUATION_ADMISSION_LEASE_EXPIRED: [
    "deny",
    "评估租约已过期",
    "容量租约在发出供应商请求前已过期，评估未向供应商发送。",
    "重新发起评估。",
  ],
  MODEL_EVALUATION_ADMISSION_NOT_CONFIGURED: [
    "deny",
    "评估准入范围未配置",
    "该租户站点尚未预置模型评估容量范围，评估被拒绝。",
    "由部署方先为该租户站点预置评估准入范围，再重试。",
  ],
  MODEL_EVALUATION_ADMISSION_POLICY_MISMATCH: [
    "deny",
    "评估策略修订不符",
    "评估输入的策略修订与已预置的准入范围不一致。",
    "使输入的 policy_revision 与准入范围登记的修订一致。",
  ],
  MODEL_EVALUATION_ADMISSION_RECOVERY_REQUIRED: [
    "deny",
    "评估租约需先恢复",
    "历史租约在恢复前不能安全复用，评估被拒绝。",
    "等待旧租约到期后再重试。",
  ],
  MODEL_EVALUATION_ADMISSION_RELEASE_UNAVAILABLE: [
    "error",
    "评估租约释放失败",
    "评估终态已记录，但容量租约未能释放，将在到期后回收。",
    "检查 PostgreSQL 连接；无需重放该评估。",
  ],
  MODEL_EVALUATION_ADMISSION_UNAVAILABLE: [
    "error",
    "评估准入存储不可用",
    "无法向权威存储申请或确认评估准入，评估未发送。",
    "检查 PostgreSQL 连接与超时后重试。",
  ],
  MODEL_EVALUATION_BUSY: [
    "error",
    "评估目录被占用",
    "评估证据根目录已被另一个评估独占，当前评估无法开始。",
    "等在途评估结束后再运行，同一目录一次只允许一个。",
  ],
  MODEL_EVALUATION_CAPACITY_EXHAUSTED: [
    "error",
    "评估并发容量已满",
    "该租户站点的并发评估容量已用尽，评估被拒绝。",
    "等在途评估完成或租约到期后重试；必要时由部署方调整上限。",
  ],
  // ---- 模型风险投影 ----
  MODEL_RISK_ABSTAINED: [
    "unknown",
    "风险投影弃权",
    "概率分布含有未知质量，风险投影弃权，不能据此判定无风险。",
    "结合其他证据人工复核；弃权不等于放行或拒绝。",
  ],
  MODEL_RISK_PROJECTED: [
    "info",
    "风险概率已投影",
    "已按批准的映射把完整概率分布投影为恶意、良性、未知三类概率。",
    "无需处理；投影只是描述性证据，不构成授权。",
  ],
  // ---- 校准评估 ----
  CALIBRATION_EVALUATED: [
    "info",
    "校准评估完成",
    "离线校准评估已完成；结果仅为描述性统计，不构成授权或已校准结论。",
    "无需处理；在校准报告中复核指标。",
  ],
  CALIBRATION_MODEL_CALL_DUPLICATE: [
    "deny",
    "模型调用重复",
    "同一模型调用证据引用在样本集中出现了多次。",
    "去除重复的模型调用引用后重新评估。",
  ],
  CALIBRATION_PROBABILITY_INVALID: [
    "deny",
    "概率取值无效",
    "样本的恶意概率不是有限数，或超出 0 到 1 的范围。",
    "修正输入数据中的概率取值后重新评估。",
  ],
  CALIBRATION_SAMPLES_EMPTY: [
    "deny",
    "样本为空",
    "评估没有任何样本。",
    "提供至少一个样本后重新评估。",
  ],
  CALIBRATION_SAMPLE_LIMIT_EXCEEDED: [
    "deny",
    "样本数量超限",
    "样本数量超过单次评估的硬上限（10000）。",
    "缩小样本集后重新评估。",
  ],
  CALIBRATION_THRESHOLDS_INVALID: [
    "deny",
    "阈值无效",
    "放行阈值大于或等于拒绝阈值，阈值不构成有效区间。",
    "调整阈值，使放行边界严格低于拒绝边界。",
  ],
  // ---- 校准证据读取 ----
  CALIBRATION_EVIDENCE_NOT_AUTHORIZED: [
    "deny",
    "校准证据未授权",
    "批次读取资格不允许读取该校准证据。",
    "核对该证据是否在冻结的批次读取资格范围内。",
  ],
  CALIBRATION_EVIDENCE_READ_AUDIT_UNAVAILABLE: [
    "error",
    "读取审计屏障不可用",
    "释放明文前必需的加密审计屏障无法写入，读取未放行。",
    "检查校准读取器专用审计日志的可写性与空间。",
  ],
  CALIBRATION_EVIDENCE_READ_AUTHORIZATION_UNAVAILABLE: [
    "error",
    "读取授权依赖不可用",
    "无法咨询权威授权依赖，校准证据读取未执行。",
    "检查授权存储（PostgreSQL）的可用性后重试。",
  ],
  CALIBRATION_EVIDENCE_READ_CANCELLED: [
    "observe",
    "校准读取被取消",
    "明文越过读取器边界前观察到取消，读取未完成。",
    "需要时通过新的读取尝试重新发起。",
  ],
  CALIBRATION_EVIDENCE_READ_CAPACITY_UNAVAILABLE: [
    "error",
    "读取预留容量不足",
    "读取器或审计日志的有界预留容量不足，读取未执行。",
    "等在途读取完成后重试，或检查审计日志容量。",
  ],
  CALIBRATION_EVIDENCE_READ_INTEGRITY_FAILED: [
    "error",
    "校准证据完整性失败",
    "证据清单、密文摘要或认证解密校验失败，内容未释放。",
    "按完整性事件处理，核对证据库对象是否损坏或被篡改。",
  ],
  CALIBRATION_EVIDENCE_READ_NOT_AUTHORIZED: [
    "deny",
    "校准证据读取被拒",
    "能力、租约、成员或当前目录校验拒绝了该校准证据读取。",
    "核对读取能力的租约与成员范围是否仍有效。",
  ],
  CALIBRATION_EVIDENCE_READ_RELEASE_PREPARED: [
    "info",
    "校准明文已预释放",
    "读取通过授权与完整性校验并写入审计屏障；不代表评估器已收到内容。",
    "无需处理。",
  ],
  CALIBRATION_EVIDENCE_READ_VAULT_UNAVAILABLE: [
    "error",
    "证据库不可用",
    "本地加密证据库无法安全读取该对象，内容未释放。",
    "检查证据库挂载、权限与磁盘状态后重试。",
  ],
  // ---- 校准评估器与报告 ----
  CALIBRATION_EVALUATOR_AUDIT_UNAVAILABLE: [
    "error",
    "评估失败审计不可用",
    "提交前的评估失败未能持久写入评估器审计。",
    "检查评估器审计日志后重试。",
  ],
  CALIBRATION_EVALUATOR_CONTENT_BINDING_MISMATCH: [
    "deny",
    "证据绑定不一致",
    "读取器返回的元数据与冻结的精确证据引用不一致。",
    "核对批次冻结引用与证据库内容，必要时重新冻结批次。",
  ],
  CALIBRATION_EVALUATOR_DECODER_LIFECYCLE_MISMATCH: [
    "error",
    "解码器状态错误",
    "解码器在未成功开始或未结束时被重复使用，属内部状态错误。",
    "联系平台管理员并附校准读取能力 ID。",
  ],
  CALIBRATION_EVALUATOR_DECODER_REJECTED: [
    "deny",
    "解码器拒绝输入",
    "类型化解码器拒绝了受控的校准记录、标签或清单。",
    "核对校准证据的记录与标签是否符合 schema v3。",
  ],
  CALIBRATION_EVALUATOR_EVIDENCE_SEQUENCE_MISMATCH: [
    "deny",
    "证据顺序不一致",
    "读取到的角色、槽位或证据超出了批次冻结的读取顺序。",
    "核对读取能力冻结的证据顺序与实际读取是否一致。",
  ],
  CALIBRATION_EVALUATOR_READER_UNAVAILABLE: [
    "error",
    "校准读取器失败",
    "专用证据读取器在暴露对象前失败，评估无法继续。",
    "查看同一读取能力的证据读取审计原因以定位。",
  ],
  CALIBRATION_REPORT_ARTIFACT_INVALID: [
    "error",
    "报告正文无效",
    "无法构造规范的受保护校准报告正文。",
    "联系平台管理员并附校准读取能力 ID。",
  ],
  CALIBRATION_REPORT_COMMIT_DEPENDENCY_UNAVAILABLE: [
    "error",
    "报告提交依赖不可用",
    "报告原子提交所依赖的数据库不可用，报告未提交。",
    "检查 PostgreSQL 可用性后重试。",
  ],
  CALIBRATION_REPORT_VAULT_UNAVAILABLE: [
    "error",
    "报告证据库不可用",
    "校准报告的写入或新鲜认证失败。",
    "检查证据库挂载与磁盘后重试。",
  ],
  // ---- 管理会话与鉴权 ----
  CONTROL_AUTH_REQUIRED: [
    "deny",
    "管理会话无效",
    "管理请求没有有效的登录会话或凭证，或会话已过期。",
    "重新登录控制台后再试。",
  ],
  CONTROL_BROWSER_SESSION_READ: [
    "info",
    "已读取会话信息",
    "对当前管理浏览器会话信息的读取已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_BROWSER_SESSION_REVOKED: [
    "info",
    "浏览器会话已撤销",
    "管理用户登出，当前浏览器会话已被撤销并记入审计日志。",
    "无需处理。",
  ],
  CONTROL_CLOCK_UNAVAILABLE: [
    "error",
    "管理服务时钟不可用",
    "管理服务无法取得可信时间，请求无法继续。",
    "稍后重试；持续出现请联系平台管理员并附管理请求 ID。",
  ],
  CONTROL_OIDC_LOGIN_COMPLETED: [
    "allow",
    "OIDC 登录已完成",
    "OIDC 回调校验通过，管理用户登录已完成。",
    "无需处理。",
  ],
  CONTROL_OIDC_LOGIN_STARTED: [
    "info",
    "OIDC 登录已发起",
    "管理用户发起了 OIDC 登录流程，尚未完成。",
    "无需处理。",
  ],
  CONTROL_OIDC_REAUTH_STARTED: [
    "info",
    "再认证已发起",
    "管理用户发起了 OIDC 再认证（step-up）流程。",
    "无需处理。",
  ],
  CONTROL_OIDC_REAUTH_VERIFIED: [
    "allow",
    "再认证已验证",
    "OIDC 身份、ACR 与认证时间验证通过；这不是原文读取或审批事实。",
    "无需处理；读取原文仍须独立审批。",
  ],
  CONTROL_RATE_LIMITED: [
    "deny",
    "管理请求被限流",
    "管理请求达到了频率上限。",
    "稍后重试，避免短时间重复提交。",
  ],
  CONTROL_RATE_UNAVAILABLE: [
    "error",
    "管理限流服务不可用",
    "管理面的限流服务暂时不可用，请求无法继续。",
    "稍后重试；持续出现请联系平台管理员并附管理请求 ID。",
  ],
  CONTROL_SCOPE_DENIED: [
    "deny",
    "管理权限不足",
    "当前身份在该租户站点范围内没有此操作所需的角色。",
    "联系管理员确认并授予所需角色。",
  ],
  CONTROL_SESSION_UNAVAILABLE: [
    "error",
    "管理会话服务不可用",
    "会话验证依赖暂时不可用，无法确认管理会话。",
    "稍后重试；持续出现请联系平台管理员并附管理请求 ID。",
  ],
  // ---- 管理查询与分页 ----
  CONTROL_AGENT_RUN_ID_INVALID: [
    "deny",
    "Agent 运行 ID 无效",
    "调用方提交的 Agent 运行 ID 不是规范格式，请求被拒绝。",
    "改用规范的 Agent 运行 ID（agt_ 前缀）后重新查询。",
  ],
  CONTROL_AGENT_RUN_READ: [
    "info",
    "已读取 Agent 运行",
    "一次 Agent 运行记录的管理读取已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_CAUSALITY_HEALTH_UNAVAILABLE: [
    "error",
    "因果索引水位不可用",
    "因果索引水位暂时无法读取。",
    "稍后重试；持续出现请联系平台管理员并附管理请求 ID。",
  ],
  CONTROL_CAUSALITY_INDEX_UNAVAILABLE: [
    "error",
    "因果索引不可用",
    "因果事件索引暂时不可用。",
    "稍后重试；持续出现请联系平台管理员并附管理请求 ID。",
  ],
  CONTROL_CAUSALITY_READ: [
    "info",
    "已读取因果链",
    "一次因果事件查询已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_CAUSALITY_REQUEST_INVALID: [
    "deny",
    "因果查询条件无效",
    "UTC 时间窗、方向或遍历上限未通过校验。",
    "修正时间窗、方向与遍历上限后重新查询。",
  ],
  CONTROL_CAUSALITY_TIMEOUT: [
    "error",
    "因果查询超时",
    "因果事件查询超过截止时间。",
    "缩小范围或稍后重试。",
  ],
  CONTROL_CURSOR_INVALID: [
    "deny",
    "分页凭证无效",
    "分页凭证的形状或签名无效，或与当前凭证、范围、页大小不匹配。",
    "重新发起查询以获取新的分页凭证。",
  ],
  CONTROL_CURSOR_UNAVAILABLE: [
    "error",
    "分页服务不可用",
    "分页凭证的签名依赖暂时不可用，无法翻页。",
    "稍后重试；持续出现请联系平台管理员并附管理请求 ID。",
  ],
  CONTROL_HEALTH_UNAVAILABLE: [
    "error",
    "索引水位不可用",
    "审计发布健康与索引水位暂时无法读取。",
    "稍后重试；持续出现请检查审计发布状态。",
  ],
  CONTROL_INDEX_UNAVAILABLE: [
    "error",
    "审计索引不可用",
    "审计索引暂时不可用，查询未能完成。",
    "稍后重试；持续出现请检查审计索引与发布状态。",
  ],
  CONTROL_MODEL_CALLS_HEALTH_UNAVAILABLE: [
    "error",
    "模型调用水位不可用",
    "模型调用索引水位暂时无法读取。",
    "稍后重试；持续出现请联系平台管理员并附管理请求 ID。",
  ],
  CONTROL_MODEL_CALLS_INDEX_UNAVAILABLE: [
    "error",
    "模型调用索引不可用",
    "模型调用索引暂时不可用。",
    "稍后重试；持续出现请联系平台管理员并附管理请求 ID。",
  ],
  CONTROL_MODEL_CALLS_READ: [
    "info",
    "已读取模型调用列表",
    "一次模型调用列表读取已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_MODEL_CALLS_REQUEST_INVALID: [
    "deny",
    "模型调用列表条件无效",
    "UTC 时间窗、页大小或分页凭证未通过校验。",
    "修正时间窗、页大小与分页凭证后重试。",
  ],
  CONTROL_QUERY_BUDGET_EXCEEDED: [
    "deny",
    "查询超出预算",
    "查询计划超出服务的确定性预算，请求被拒绝，原样重试无效。",
    "缩小时间范围或细化条件；精确 ID 查询请联系管理员。",
  ],
  CONTROL_QUERY_CAPACITY_EXHAUSTED: [
    "error",
    "调查查询繁忙",
    "单实例的调查查询在途容量已占满，本次查询被拒绝。",
    "稍后重试。",
  ],
  CONTROL_QUERY_EXECUTED: [
    "info",
    "已执行调查查询",
    "一次调查查询已执行并记入审计日志，审计只保存查询摘要。",
    "无需处理。",
  ],
  CONTROL_QUERY_INVALID: [
    "deny",
    "查询计划无效",
    "时间范围、条件或页大小未通过校验，未访问索引。",
    "修正 UTC 时间范围、条件和页大小后重新查询。",
  ],
  CONTROL_QUERY_TIMEOUT: [
    "error",
    "调查查询超时",
    "调查查询超过截止时间，未返回结果。",
    "缩小范围或稍后重试。",
  ],
  // ---- 管理案件分析与任务 ----
  CONTROL_CASES_READ: [
    "info",
    "已读取案件列表",
    "一次案件列表的管理读取已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_CASE_ANALYSIS_BUSY: [
    "error",
    "案件分析繁忙",
    "案件分析的在途容量已占满，分析任务未创建。",
    "稍后用原幂等键与参数重试。",
  ],
  CONTROL_CASE_ANALYSIS_CREATED: [
    "info",
    "案件分析任务已创建",
    "已创建案件分析任务（HTTP 202），不代表分析已完成。",
    "用任务 ID 读取任务状态。",
  ],
  CONTROL_CASE_ANALYSIS_REPLAYED: [
    "info",
    "案件分析任务被重放",
    "相同幂等键与参数的请求返回了已有分析任务，没有新建。",
    "用任务 ID 读取任务状态。",
  ],
  CONTROL_CASE_ANALYSIS_STORE_UNAVAILABLE: [
    "error",
    "案件分析存储不可用",
    "案件分析存储暂时不可用，写入结果可能未知。",
    "保留原幂等键与参数重试，以确认任务是否已创建。",
  ],
  CONTROL_CASE_ANALYSIS_TARGET_UNAVAILABLE: [
    "deny",
    "案件分析目标不可用",
    "当前身份和范围内找不到可分析的案件。",
    "核对案件 ID 与所属租户站点。",
  ],
  CONTROL_CASE_ID_INVALID: [
    "deny",
    "案件 ID 无效",
    "调用方提交的案件 ID 不是规范格式，请求被拒绝。",
    "改用规范的案件 ID（case_ 前缀）后重新请求。",
  ],
  CONTROL_IDEMPOTENCY_CONFLICT: [
    "deny",
    "幂等键冲突",
    "该幂等键已绑定到另一组参数，本次请求被拒绝。",
    "沿用原请求的全部参数，或换用新的幂等键。",
  ],
  CONTROL_IDEMPOTENCY_KEY_INVALID: [
    "deny",
    "幂等键无效",
    "幂等键缺失，或不是 16 至 128 字节的合规单个值。",
    "提供格式合规的单个 Idempotency-Key 后重试。",
  ],
  CONTROL_IDEMPOTENCY_UNAVAILABLE: [
    "error",
    "幂等服务不可用",
    "幂等处理依赖暂时不可用，请求未被处理。",
    "稍后用原幂等键与参数重试。",
  ],
  CONTROL_JOB_ID_INVALID: [
    "deny",
    "任务 ID 无效",
    "调用方提交的任务 ID 不是规范格式，请求被拒绝。",
    "改用规范的任务 ID（job_ 前缀）后重新查询。",
  ],
  CONTROL_ADMIN_JOBS_READ: [
    "info",
    "已读取全部任务列表",
    "一次管理员全部任务列表的读取已记入审计日志，列表含提交者引用。",
    "无需处理。",
  ],
  CONTROL_ADMIN_JOB_LIST_BUSY: [
    "error",
    "全部任务列表繁忙",
    "案件与证据相关读取的在途容量已占满，本次全部任务列表请求被拒绝。",
    "稍后重试。",
  ],
  CONTROL_ADMIN_JOB_LIST_REQUEST_INVALID: [
    "deny",
    "全部任务列表请求无效",
    "全部任务列表只接受可选的 cursor 参数，其余形状被拒绝。",
    "去掉多余参数后重新读取，或从第一页开始。",
  ],
  CONTROL_ADMIN_JOB_STORE_UNAVAILABLE: [
    "error",
    "任务存储不可用",
    "管理服务暂时无法访问任务状态存储，全部任务列表读取未完成。",
    "稍后重试；持续出现请联系平台管理员并附管理请求 ID。",
  ],
  CONTROL_SAVED_VIEW_CREATED: [
    "info",
    "已保存检索视图",
    "一个检索视图已按名称保存，只保存检索条件，不保存结果。",
    "无需处理。",
  ],
  CONTROL_SAVED_VIEW_DELETED: [
    "info",
    "已删除检索视图",
    "一个本人保存的检索视图已删除，删除的只是保存的条件。",
    "无需处理。",
  ],
  CONTROL_SAVED_VIEW_ID_INVALID: [
    "deny",
    "检索视图标识无效",
    "删除请求中的视图标识格式不对，请求被拒绝。",
    "使用列表返回的视图标识重试。",
  ],
  CONTROL_SAVED_VIEW_NAME_TAKEN: [
    "deny",
    "视图名称已存在",
    "本人已有同名的检索视图，未保存任何内容。",
    "换一个名称后保存。",
  ],
  CONTROL_SAVED_VIEW_NOT_FOUND: [
    "deny",
    "检索视图不存在",
    "没有找到本人的这个检索视图，可能已被删除。",
    "刷新列表后重试。",
  ],
  CONTROL_SAVED_VIEW_REQUEST_INVALID: [
    "deny",
    "检索视图请求无效",
    "保存的检索条件未通过校验（格式、时间窗、上限或含游标），未保存。",
    "修正检索条件后重新保存。",
  ],
  CONTROL_SAVED_VIEW_STORE_UNAVAILABLE: [
    "error",
    "检索视图存储不可用",
    "检索视图存储暂时无法访问，本次操作未完成。",
    "稍后重试；持续出现请联系平台管理员并附管理请求 ID。",
  ],
  CONTROL_SAVED_VIEWS_READ: [
    "info",
    "已读取检索视图列表",
    "一次本人检索视图列表的读取已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_JOB_LIST_BUSY: [
    "error",
    "任务列表繁忙",
    "案件与证据相关读取的在途容量已占满，本次任务列表请求被拒绝。",
    "稍后重试。",
  ],
  CONTROL_JOB_LIST_REQUEST_INVALID: [
    "deny",
    "任务列表请求无效",
    "任务列表只接受可选的 cursor 参数，其余形状被拒绝。",
    "去掉多余参数后重新读取，或从第一页开始。",
  ],
  CONTROL_JOBS_READ: [
    "info",
    "已读取任务列表",
    "一次本人任务列表的管理读取已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_JOB_READ: [
    "info",
    "已读取任务状态",
    "一次任务状态的管理读取已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_JOB_STORE_UNAVAILABLE: [
    "error",
    "任务存储不可用",
    "管理服务暂时无法访问任务状态存储，读取未完成。",
    "稍后重试；持续出现请联系平台管理员并附管理请求 ID。",
  ],
  // ---- 管理证据访问与保留锁 ----
  CONTROL_EVIDENCE_ACCESS_BUSY: [
    "error",
    "证据访问服务繁忙",
    "证据访问申请读取的在途容量已占满，本次请求被拒绝。",
    "稍后重试。",
  ],
  CONTROL_EVIDENCE_ACCESS_ID_INVALID: [
    "deny",
    "访问申请 ID 无效",
    "调用方提交的访问申请 ID 不是规范格式，请求被拒绝。",
    "改用规范的访问申请 ID（access_ 前缀）后重新查询。",
  ],
  CONTROL_EVIDENCE_ACCESS_LIST_READ: [
    "info",
    "已读取访问申请列表",
    "一次证据访问申请列表的管理读取已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_EVIDENCE_ACCESS_LIST_REQUEST_INVALID: [
    "deny",
    "访问申请列表请求无效",
    "列表请求缺少或写错了 view 等参数，请求被拒绝。",
    "指定 view=mine 或 view=review 后重新读取。",
  ],
  CONTROL_EVIDENCE_ACCESS_READ: [
    "info",
    "已读取访问申请",
    "一次证据访问申请详情的管理读取已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_EVIDENCE_ACCESS_READ_NOT_AVAILABLE: [
    "deny",
    "访问申请不可用",
    "当前身份和范围内查不到该访问申请。",
    "核对申请 ID 与所属租户站点。",
  ],
  CONTROL_EVIDENCE_ACCESS_READ_REQUEST_INVALID: [
    "deny",
    "访问申请查询无效",
    "访问申请详情查询的参数未通过校验，请求被拒绝。",
    "核对申请 ID 与请求参数后重试。",
  ],
  CONTROL_EVIDENCE_ACCESS_READ_STORE_UNAVAILABLE: [
    "error",
    "访问申请存储不可用",
    "管理服务暂时无法访问访问申请存储，读取未完成。",
    "稍后重试；持续出现请联系平台管理员并附管理请求 ID。",
  ],
  CONTROL_EVIDENCE_HOLD_CREATED: [
    "info",
    "证据保留锁已创建",
    "已为案件证据创建保留锁，暂停其物理删除；读取审批与到期规则不变。",
    "无需处理。",
  ],
  CONTROL_EVIDENCE_HOLD_CREATE_REPLAYED: [
    "info",
    "保留锁创建被重放",
    "相同幂等键的创建请求返回了原保留锁，没有新建，期限不变。",
    "无需处理。",
  ],
  CONTROL_EVIDENCE_HOLD_READ: [
    "info",
    "已读取保留锁历史",
    "一次案件保留锁历史的管理读取已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_EVIDENCE_HOLD_RELEASED: [
    "info",
    "证据保留锁已释放",
    "保留锁已释放，该证据不再被暂停删除。",
    "无需处理。",
  ],
  CONTROL_EVIDENCE_HOLD_RELEASE_REPLAYED: [
    "info",
    "保留锁释放被重放",
    "相同幂等键的释放请求返回了已提交的释放结果。",
    "无需处理。",
  ],
  // ---- 管理校准报告读取 ----
  CONTROL_CALIBRATION_REPORT_BUSY: [
    "error",
    "校准报告查询繁忙",
    "校准报告读取的在途容量已占满，本次读取被拒绝。",
    "稍后重试。",
  ],
  CONTROL_CALIBRATION_REPORT_HISTORY_SCOPE_DENIED: [
    "deny",
    "缺少报告历史权限",
    "查询含校准报告条件，但调用者在同一范围没有审计管理员角色。",
    "请管理员授予审计管理员角色，或去掉报告条件。",
  ],
  CONTROL_CALIBRATION_REPORT_ID_INVALID: [
    "deny",
    "校准报告 ID 无效",
    "调用方提交的校准报告 ID 不是规范格式，请求被拒绝。",
    "改用规范的校准报告 ID（calr_ 前缀）后重新查询。",
  ],
  CONTROL_CALIBRATION_REPORT_READ: [
    "info",
    "已读取校准报告",
    "一次校准报告的管理读取已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_CALIBRATION_REPORT_READ_REQUEST_INVALID: [
    "deny",
    "校准报告请求无效",
    "校准报告读取请求的路径或参数未通过校验，请求被拒绝。",
    "核对报告 ID 与请求参数后重试。",
  ],
  CONTROL_CALIBRATION_REPORT_STORE_UNAVAILABLE: [
    "error",
    "校准报告存储不可用",
    "管理服务暂时无法访问校准报告存储，读取未完成。",
    "稍后重试；持续出现请联系平台管理员并附管理请求 ID。",
  ],
  // ---- 管理导出读取 ----
  CONTROL_EXPORTS_READ: [
    "info",
    "已读取导出列表",
    "一次导出列表的管理读取已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_EXPORT_BUSY: [
    "error",
    "导出服务繁忙",
    "导出相关读取的在途容量已占满，本次请求被拒绝。",
    "稍后重试。",
  ],
  CONTROL_EXPORT_LIST_REQUEST_INVALID: [
    "deny",
    "导出列表请求无效",
    "列表请求缺少或写错了 view 等参数，请求被拒绝。",
    "指定 view=mine 或 view=review 后重新读取。",
  ],
  CONTROL_EXPORT_READ: [
    "info",
    "已读取导出详情",
    "一次导出详情的管理读取已记入审计日志。",
    "无需处理。",
  ],
  CONTROL_EXPORT_STORE_UNAVAILABLE: [
    "error",
    "导出状态存储不可用",
    "导出状态存储暂时不可用；写操作的结果可能未知。",
    "写操作保留原幂等键与参数重试；读取可直接重试。",
  ],
  // ---- 案件、证据访问与导出事实 ----
  CASE_CLOSED: ["info", "案件已关闭", "案件关闭事件已提交。", "无需处理。"],
  CASE_CREATED: ["info", "案件已创建", "案件创建事件已提交，对应案件已建立。", "无需处理。"],
  CASE_EVIDENCE_ADDED: ["info", "证据已关联案件", "一项证据已关联到案件。", "无需处理。"],
  EVIDENCE_ACCESS_APPROVED: [
    "allow",
    "证据访问已批准",
    "访问申请已获独立审批人批准并设定了有限期限；不表示原文已被读取。",
    "申请人须在批准期限内读取，逾期需重新申请。",
  ],
  EVIDENCE_ACCESS_DENIED: [
    "deny",
    "证据访问被拒绝",
    "访问申请已被审批人拒绝，不会生成读取资格。",
    "查看审批理由；仍需访问时补充依据重新申请。",
  ],
  EVIDENCE_ACCESS_REQUESTED: [
    "info",
    "证据访问已申请",
    "已提交敏感原文的证据访问申请，等待另一位审批人决策。",
    "由具备审批权限的另一主体处理该申请。",
  ],
  EXPORT_APPROVAL_REPLAYED: [
    "info",
    "导出批准被重放",
    "相同幂等键的批准请求返回了已提交的批准结果。",
    "无需处理。",
  ],
  EXPORT_APPROVED: [
    "allow",
    "导出已批准",
    "导出申请已获批准并设定有效期；不表示导出包已被下载。",
    "有读取权限的主体须在有效期内完成 step-up 后下载。",
  ],
  EXPORT_DENIAL_REPLAYED: [
    "info",
    "导出拒绝被重放",
    "相同幂等键的拒绝请求返回了已提交的拒绝结果。",
    "无需处理。",
  ],
  EXPORT_DENIED: [
    "deny",
    "导出被拒绝",
    "导出申请已被审批人拒绝。",
    "查看审批理由；仍需导出时重新提交申请。",
  ],
  EXPORT_DOWNLOADED: [
    "info",
    "导出包已下载",
    "加密的导出元数据包已被下载，审计记录了读取的字节数。",
    "无需处理。",
  ],
  EXPORT_REQUESTED: [
    "info",
    "导出已申请",
    "已提交案件导出申请，等待独立审批人处理。",
    "由具备审批权限的另一主体审批。",
  ],
  EXPORT_REQUEST_REPLAYED: [
    "info",
    "导出申请被重放",
    "相同幂等键的导出申请返回了原申请，没有新建。",
    "无需处理。",
  ],
  WORKBENCH_OVERVIEW_READ: [
    "info",
    "已读取工作台概览",
    "一次工作台概览的管理读取已记入审计日志。",
    "无需处理。",
  ],
  // ---- Outbox 发布器 ----
  OUTBOX_INDEX_UNAVAILABLE: [
    "error",
    "Outbox 索引写入失败",
    "写入审计索引（ClickHouse）失败，事件保持未确认并稍后重试。",
    "检查 ClickHouse 连通性与目标表，恢复后发布器会自动重试。",
  ],
  OUTBOX_INTEGRITY_CONFLICT: [
    "error",
    "Outbox 完整性冲突",
    "索引中已有同一事件 ID 但内容摘要不同，发布被拒绝且保持未确认。",
    "保留现场并联系平台管理员，排查事件被篡改或重复生产。",
  ],
  OUTBOX_INVALID_EVENT: [
    "error",
    "Outbox 事件无效",
    "事件未通过结构、作用域或大小校验，保持未确认并延迟重试。",
    "核对事件生产者版本与作用域；历史稀疏行需运维处理。",
  ],
  // ---- 样例数据与旧版本兼容 ----
  REQUEST_ACCEPTED: [
    "allow",
    "请求已受理",
    "准入阶段通过，边缘已受理这次完整的 HTTP 请求；不代表后续检查通过。",
    "无需处理；后续阶段结果见同一请求的时间线。",
  ],
  REQUEST_DENIED: [
    "deny",
    "请求被拒绝",
    "该请求的终态为拒绝；具体原因见前序阶段的原因码。",
    "在同一请求的时间线中定位触发拒绝的阶段与原因码。",
  ],
  MODEL_PROVIDER_UNAVAILABLE: [
    "error",
    "模型供应商不可用",
    "无法连接模型供应商，本次评估没有取得结果。",
    "稍后重试；持续出现请检查供应商状态与出站网络。",
  ],
};
