import { useQueryClient } from "@tanstack/react-query";
import { useEffect, useRef, useState } from "react";
import type { ControlClient } from "../api.ts";
import type { WriteResult } from "../security/guarded.ts";
import { guardedQueryKey } from "../security/guarded-query.ts";
import { useGuardedMutation, usePendingOperations } from "../security/hooks";
import type { OperationSnapshot } from "../security/pending-operations.ts";
import type { ScopedResponse } from "../security/scope.ts";
import { useSession } from "../security/SessionProvider";
import type { Owner } from "./operations.ts";
import { withStepUp } from "./step-up.ts";
import { useStepUp } from "./WorkRoot";

/** The unresolved write a page owns, for banners shown while its dialog is closed. */
export function useUnresolved(owner: Owner): OperationSnapshot | null {
  return usePendingOperations().find(owner) ?? null;
}

export type WriteSpec<TVars, T extends ScopedResponse> = {
  /** Short name shown in the pending-operations chip. */
  label: string;
  /** The fixed `/control/v1/...` path, frozen at submit time. */
  path: (vars: TVars) => string;
  body?: (vars: TVars) => unknown;
  /** Runs with a copy of the variables taken at submit time, never with live form state. */
  run: (
    client: ControlClient,
    vars: TVars,
    context: { signal: AbortSignal; idempotencyKey: string },
  ) => Promise<T>;
  /** Claims this control's unresolved operations in the registry. */
  owner: Owner;
  /** Key prefixes (without the session epoch) to mark stale once a write is confirmed. */
  invalidate?: readonly (readonly unknown[])[];
};

export type Write<TVars, T extends ScopedResponse> = Readonly<{
  /** The unresolved write of this control (it survives navigation), or `null`. */
  operation: OperationSnapshot | null;
  /** A request is on its way: just submitted, or an earlier one still in flight. */
  busy: boolean;
  /** The server refused the last first attempt; nothing was written, the form stays editable. */
  rejection: unknown;
  confirmed: T | null;
  submit: (vars: TVars) => Promise<WriteResult<T>>;
  /** Sends the frozen request again, byte for byte, under its original key. */
  retry: () => Promise<WriteResult<T> | null>;
  /** Forgets the last rejection or confirmation (a new dialog starts clean). */
  dismiss: () => void;
}>;

/**
 * One write kind of one control, on top of `useGuardedMutation` and the pending-operation
 * registry. The request (path, key, body) is frozen when `submit` runs; an unknown outcome stays
 * in the registry and can only be continued with `retry`. The idempotency key is generated by the
 * framework and is never a form field. When the server asks for an MFA step-up the same frozen
 * request waits for it and is then sent again, unchanged.
 */
export function useWrite<TVars, T extends ScopedResponse>(
  spec: WriteSpec<TVars, T>,
  onConfirmed?: (response: T) => void,
): Write<TVars, T> {
  const { runtime } = useSession();
  const queryClient = useQueryClient();
  const stepUp = useStepUp();
  const pending = usePendingOperations();
  const operation = pending.find(spec.owner) ?? null;
  const [rejection, setRejection] = useState<unknown>(null);
  const [confirmed, setConfirmed] = useState<T | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const latch = useRef(false);
  const callback = useRef(onConfirmed);
  useEffect(() => {
    callback.current = onConfirmed;
  });

  const mutation = useGuardedMutation<TVars, T>({
    label: spec.label,
    method: "POST",
    path: spec.path,
    body: spec.body,
    execute: (client, vars, context) =>
      withStepUp(stepUp, context.signal, () => spec.run(client, vars, context)),
  });

  function settle(result: WriteResult<T>): WriteResult<T> {
    if (result.kind === "confirmed") {
      setConfirmed(result.response);
      setRejection(null);
      const epoch = runtime.store.getState().epoch;
      for (const prefix of spec.invalidate ?? []) {
        void queryClient.invalidateQueries({ queryKey: guardedQueryKey(epoch, prefix) });
      }
      callback.current?.(result.response);
    } else if (result.kind === "rejected") {
      setRejection(result.error);
    }
    return result;
  }

  async function run(send: () => Promise<WriteResult<T>>): Promise<WriteResult<T>> {
    // A ref closes the window between a click and the next paint: a double click sends one request.
    if (latch.current) return { kind: "stale" };
    latch.current = true;
    setSubmitting(true);
    try {
      return settle(await send());
    } finally {
      latch.current = false;
      setSubmitting(false);
    }
  }

  return {
    operation,
    busy: submitting || operation?.phase === "inflight",
    rejection,
    confirmed,
    submit: (vars) => {
      if (operation) return Promise.resolve({ kind: "stale" });
      setRejection(null);
      setConfirmed(null);
      return run(() => mutation.submit(vars));
    },
    retry: async () => {
      if (!operation || operation.phase !== "unknown") return null;
      setRejection(null);
      return run(() => mutation.retry(operation.id));
    },
    dismiss: () => {
      setRejection(null);
      setConfirmed(null);
    },
  };
}
