#!/usr/bin/env python3
"""Regenerate local schema expectations from migrations in an owned temporary DB.

Requires the development PostgreSQL container. Only the randomly named reference
DB is created/deleted; the developer's data volume is never reset.
"""
import hashlib
import json
import os
from pathlib import Path
import subprocess
import uuid

ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = """
CREATE TEMP VIEW dev_schema_objects AS
SELECT 'table'::text AS kind, c.relname::text AS table_name, c.relname::text AS name,
       c.relkind::text AS definition
FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='xshield' AND c.relkind IN ('r','p')
UNION ALL
SELECT 'column', c.relname, a.attname,
       format_type(a.atttypid,a.atttypmod) || '|' || a.attnotnull::text || '|' ||
       coalesce(pg_get_expr(d.adbin,d.adrelid),'')
FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid
JOIN pg_namespace n ON n.oid=c.relnamespace
LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
WHERE n.nspname='xshield' AND c.relkind IN ('r','p') AND a.attnum>0 AND NOT a.attisdropped
UNION ALL
SELECT 'constraint', c.relname, p.conname,
       pg_get_constraintdef(p.oid) || '|' || p.convalidated::text
FROM pg_constraint p JOIN pg_class c ON c.oid=p.conrelid
JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='xshield'
UNION ALL
SELECT 'index', tablename, indexname, indexdef FROM pg_indexes WHERE schemaname='xshield';
"""

def quote(value):
    return "'" + str(value).replace("'", "''") + "'"


def main():
    database = 'xshield_schema_' + uuid.uuid4().hex[:12]
    project = os.environ.get('XSHIELD_DEV_COMPOSE_PROJECT', 'xshield-dev')
    user = os.environ.get('XSHIELD_DEV_POSTGRES_USER', 'xshield_dev')
    docker = ['docker', 'compose', '-p', project, '-f', str(ROOT / 'docker-compose.dev.yml'), 'exec', '-T', 'postgres']
    def sql(statement):
        return subprocess.check_output(docker + ['psql', '-X', '-qAt', '-v', 'ON_ERROR_STOP=1', '-U', user, '-d', database], input=statement, text=True)
    subprocess.run(docker + ['createdb', '-U', user, database], check=True)
    previous = {}
    rows = []
    hashes = []
    try:
        for file in sorted((ROOT / 'migrations').glob('*.sql')):
            phase = file.name[:4]
            if phase > '0054': break
            sql(file.read_text())
            if phase < '0040': continue
            payload = sql(SNAPSHOT + "SELECT coalesce(json_agg(o),'[]') FROM dev_schema_objects o;")
            objects = json.loads(payload)
            current = {(o['kind'], o['table_name'], o['name']): o['definition'] for o in objects}
            for key, value in sorted(current.items()):
                if previous.get(key) != value:
                    rows.append('(' + ','.join(map(quote, (phase,) + key + (value,))) + ')')
            previous = current
            if phase != '0040': hashes.append('(' + ','.join(map(quote, (phase, hashlib.sha256(file.read_bytes()).hexdigest()))) + ')')
    finally:
        subprocess.run(docker + ['dropdb', '-U', user, '--if-exists', database], check=True)
    out = '-- Generated by scripts/generate_dev_postgres_schema.py; local development only.\n'
    out += SNAPSHOT
    out += 'CREATE TEMP TABLE dev_expected_objects (phase text, kind text, table_name text, name text, definition text);\n'
    out += 'INSERT INTO dev_expected_objects VALUES\n' + ',\n'.join(rows) + ';\n'
    out += 'CREATE TEMP TABLE dev_expected_checksums (phase text PRIMARY KEY, sha256 text);\n'
    out += 'INSERT INTO dev_expected_checksums VALUES\n' + ',\n'.join(hashes) + ';\n'
    out += """
-- Whether an object reached the definition a phase recorded for it. A later
-- migration may redefine an object (0052 widens a CHECK created by 0044), so a
-- definition recorded by any later phase counts as reached too. A missing
-- object (NULL definition) never has.
CREATE FUNCTION pg_temp.dev_definition_reached(p_phase text, p_kind text, p_table text, p_name text, p_actual text)
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM dev_expected_objects later
    WHERE later.kind = p_kind AND later.table_name = p_table AND later.name = p_name
      AND later.phase >= p_phase AND later.definition = p_actual)
$$;

CREATE FUNCTION pg_temp.dev_assert_schema(p_phase text) RETURNS void LANGUAGE plpgsql AS $$
DECLARE missing text;
BEGIN
  SELECT e.kind || ':' || e.table_name || '.' || e.name INTO missing
  FROM dev_expected_objects e LEFT JOIN dev_schema_objects a
    USING(kind, table_name, name)
  WHERE e.phase=p_phase
    AND NOT pg_temp.dev_definition_reached(e.phase, e.kind, e.table_name, e.name, a.definition)
  ORDER BY e.kind, e.table_name, e.name LIMIT 1;
  IF missing IS NOT NULL THEN
    RAISE EXCEPTION 'dev migration % schema mismatch: %', p_phase, missing;
  END IF;
END $$;
"""
    (ROOT / 'scripts/dev_postgres_schema.sql').write_text(out)
    print('Wrote schema expectations:', len(rows), 'objects')

if __name__ == '__main__':
    main()
