import { densities, fonts, type Palette, palettes, radii } from "./tokens.ts";

/** `surfaceSubtle` -> `--xs-surface-subtle`, `ink2` -> `--xs-ink-2`. */
export function cssVariableName(key: string): string {
  const kebab = key
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/([A-Za-z])(\d)/g, "$1-$2")
    .toLowerCase();
  return `--xs-${kebab}`;
}

function declarations(values: Record<string, string>, indent: string): string {
  return Object.entries(values)
    .map(([key, value]) => `${indent}${cssVariableName(key)}: ${value};`)
    .join("\n");
}

function paletteValues(palette: Palette): Record<string, string> {
  return { ...palette };
}

/**
 * The static CSS variable layer. Light is the default; dark applies either through the
 * operating-system preference (unless the user pinned light) or through an explicit
 * `data-theme="dark"`. No script is required to follow the system preference, so the first
 * paint is already correct under the strict `style-src 'self'` policy.
 */
export function themeCss(): string {
  const base = {
    fontSans: fonts.sans,
    fontMono: fonts.mono,
    radiusControl: radii.control,
    radiusPanel: radii.panel,
  };
  const dark = declarations(paletteValues(palettes.dark), "    ");
  return [
    "/* Generated by `npm run theme:css` from src/theme/tokens.ts. Do not edit by hand. */",
    ":root {",
    "  color-scheme: light;",
    declarations(base, "  "),
    declarations(paletteValues(palettes.light), "  "),
    declarations(densities.comfortable, "  "),
    "}",
    "",
    "@media (prefers-color-scheme: dark) {",
    '  :root:not([data-theme="light"]) {',
    "    color-scheme: dark;",
    dark,
    "  }",
    "}",
    "",
    ':root[data-theme="dark"] {',
    "  color-scheme: dark;",
    declarations(paletteValues(palettes.dark), "  "),
    "}",
    "",
    ':root[data-density="compact"] {',
    declarations(densities.compact, "  "),
    "}",
    "",
  ].join("\n");
}
